<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'FalconCPPLicenseLinter' => 'lint/linter/FalconCPPLicenseLinter.php',
    'FalconExceptionTest' => 'unit/tests/FalconExceptionTests.php',
    'FalconJsonParserTest' => 'unit/tests/FalconJsonParserTest.php',
    'FalconLintEngine' => 'lint/FalconLintEngine.php',
    'FalconPosixSubProcessTest' => 'unit/tests/FalconPosixSubProcessTest.php',
    'FalconUnitTestBase' => 'unit/FalconUnitTestBase.php',
    'FalconUnitTestEngine' => 'unit/FalconUnitTestEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'FalconCPPLicenseLinter' => 'ArcanistLinter',
    'FalconExceptionTest' => 'FalconUnitTestBase',
    'FalconJsonParserTest' => 'FalconUnitTestBase',
    'FalconLintEngine' => 'ArcanistLintEngine',
    'FalconPosixSubProcessTest' => 'FalconUnitTestBase',
    'FalconUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
));
